"""tag

Revision ID: 012bb5f04223
Revises: 687c7ca8ad8c
Create Date: 2022-02-26 16:46:54.544292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012bb5f04223'
down_revision = '687c7ca8ad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('article_tags', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_tags', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
